oc_user:
    resource: "@OCUserBundle/Resources/config/routing.yml"
    prefix:   /

# src/OC/PlatformBundle/Resources/config/routing.yml

appliweb:
    resource: "@appliwebBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: OCUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
