<?php

namespace appliwebBundle\Repository;

/**
 * Cat_goodiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cat_goodiesRepository extends \Doctrine\ORM\EntityRepository
{
}
