<?php

namespace appliwebBundle\Repository;

/**
 * Cat_foodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cat_foodRepository extends \Doctrine\ORM\EntityRepository
{
}
