<?php

namespace appliwebBundle\Repository;

/**
 * GoodiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodiesRepository extends \Doctrine\ORM\EntityRepository
{
}
