<?php

namespace appliwebBundle\Repository;

/**
 * Vote_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Vote_userRepository extends \Doctrine\ORM\EntityRepository
{
}
